repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-executables-have-shebangs
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: check-yaml
          - id: check-json
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.31.0
      hooks:
          - id: eslint
            types: [file]
            files: \.jsx?$
            args: [--fix]
            additional_dependencies:
                - eslint
                - eslint-config-prettier
                - eslint-config-react-app
                - eslint-plugin-sonarjs
                - eslint-plugin-react
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.4
      hooks:
          - id: prettier
            files: \.jsx?$
            additional_dependencies:
                - prettier
                - '@trivago/prettier-plugin-sort-imports'
